import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar: intro + an auto-generated list of API reference pages.
const sidebars: SidebarsConfig = {
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Examples',
            collapsed: true,
            link: { type: 'generated-index' },
            items: [{ type: 'autogenerated', dirName: 'examples' }],
        },
        {
            type: 'category',
            label: 'API Reference',
            collapsed: false,
            link: { type: 'generated-index' },
            items: [{ type: 'autogenerated', dirName: 'api-reference' }],
        },
    ],
};

export default sidebars;
